/**
 * PDF Export Utility
 * 
 * Exports the current scenario state to a summary PDF document.
 */

import jsPDF from 'jspdf';

/**
 * Export current scenario to PDF
 */
export async function exportScenarioToPDF(scenarioData) {
    const {
        projectStatus,
        virtualResources,
        totalDeficit,
        months,
        metadata
    } = scenarioData;

    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Title
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Capacity Scenario Report', margin, y);
    y += 15;

    // Metadata
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100);
    pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
    y += 6;
    if (metadata?.file_name) {
        pdf.text(`Source: ${metadata.file_name}`, margin, y);
        y += 6;
    }
    y += 10;

    // Summary Box
    pdf.setFillColor(245, 245, 250);
    pdf.setDrawColor(200, 200, 220);
    pdf.roundedRect(margin, y, pageWidth - (margin * 2), 30, 3, 3, 'FD');

    y += 10;
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0);

    if (totalDeficit === 0) {
        pdf.setTextColor(34, 139, 34);
        pdf.text('✓ All Projects Fully Staffed', margin + 10, y);
    } else {
        pdf.setTextColor(200, 50, 50);
        pdf.text(`⚠ Total Deficit: ${totalDeficit.toLocaleString()} hours`, margin + 10, y);
    }

    y += 8;
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.setFont('helvetica', 'normal');
    const projectCount = Object.keys(projectStatus).length;
    const staffedCount = Object.values(projectStatus).filter(p => p.overallStatus === 'staffed').length;
    pdf.text(`${staffedCount} of ${projectCount} projects fully staffed`, margin + 10, y);

    y += 25;

    // Virtual Resources Section
    if (virtualResources.length > 0) {
        pdf.setFontSize(16);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(0);
        pdf.text('Virtual Resources Added', margin, y);
        y += 10;

        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');

        virtualResources.forEach((resource, idx) => {
            if (y > 270) {
                pdf.addPage();
                y = 20;
            }

            const hoursPerMonth = resource.hoursPerMonth || 160;
            pdf.text(
                `${idx + 1}. ${resource.team} / ${resource.role} / ${resource.location} - +${hoursPerMonth} hrs/month`,
                margin + 5,
                y
            );
            y += 6;
        });

        y += 10;
    }

    // Priority List Section
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0);
    pdf.text('Project Priority List', margin, y);
    y += 10;

    // Table header
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setFillColor(240, 240, 245);
    pdf.rect(margin, y - 4, pageWidth - (margin * 2), 8, 'F');

    pdf.text('#', margin + 2, y);
    pdf.text('Project', margin + 15, y);
    pdf.text('Team/Role/Location', margin + 80, y);
    pdf.text('Status', pageWidth - margin - 25, y);
    y += 8;

    // Project rows
    pdf.setFont('helvetica', 'normal');

    const sortedProjects = Object.values(projectStatus)
        .sort((a, b) => a.priority - b.priority);

    sortedProjects.forEach((project) => {
        if (y > 270) {
            pdf.addPage();
            y = 20;
        }

        // Priority number
        pdf.text(project.priority.toString(), margin + 2, y);

        // Project name (truncated if needed)
        const projectName = project.name.length > 30
            ? project.name.substring(0, 27) + '...'
            : project.name;
        pdf.text(projectName, margin + 15, y);

        // Team/Role/Location
        const bucket = `${project.team}/${project.role}/${project.location}`;
        const bucketTruncated = bucket.length > 35
            ? bucket.substring(0, 32) + '...'
            : bucket;
        pdf.text(bucketTruncated, margin + 80, y);

        // Status with color
        if (project.overallStatus === 'staffed') {
            pdf.setTextColor(34, 139, 34);
            pdf.text('Staffed', pageWidth - margin - 25, y);
        } else if (project.overallStatus === 'partial') {
            pdf.setTextColor(200, 150, 0);
            pdf.text('Partial', pageWidth - margin - 25, y);
        } else {
            pdf.setTextColor(200, 50, 50);
            pdf.text('Unstaffed', pageWidth - margin - 25, y);
        }
        pdf.setTextColor(0);

        y += 6;
    });

    // Footer
    const footerY = pdf.internal.pageSize.getHeight() - 15;
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text('Generated by What-If Simulation Dashboard', margin, footerY);
    pdf.text(`Page 1`, pageWidth - margin - 15, footerY);

    // Save the PDF
    pdf.save(`capacity-scenario-${new Date().toISOString().split('T')[0]}.pdf`);
}

/**
 * Export scenario data as JSON (for debugging or data transfer)
 */
export function exportScenarioAsJSON(scenarioData) {
    const dataStr = JSON.stringify(scenarioData, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);

    const link = document.createElement('a');
    link.href = url;
    link.download = `scenario-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
